### Home Route
GET http://localhost:8080/

###

### Get All Contacts
GET http://localhost:8080/contacts


###

### Get Contact By ID
GET http://localhost:8080/contacts/6a461bb2a8e3dc5bf5f8edf4

###

### Create Contact

POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Isaac",
    "lastName": "Newton",
    "email": "isaacnewton@gmail.com",
    "favoriteColor": "Blue",
    "birthday": "1998-04-20"
}

### Update Contact

PUT http://localhost:8080/contacts/6a57d29117afc561fe62607a
Content-Type: application/json

{
    "firstName": "Isaac",
    "lastName": "Newton",
    "email": "isaacnewton@gmail.com",
    "favoriteColor": "White",
    "birthday": "1998-04-20"
}

### Delete Contact

DELETE http://localhost:8080/contacts/6a57d29117afc561fe62607a

### Home route(Render)
GET  https://cse341-contacts-h7ua.onrender.com

###

### Get All Contacts(Render)
GET https://cse341-contacts-h7ua.onrender.com/contacts

###

### Get Contact by ID(Render)
GET https://cse341-contacts-h7ua.onrender.com/contacts/6a461b5da8e3dc5bf5f8edf0